name: todo_app_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  dartz: ^0.10.1
  dio: ^4.0.6
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  firebase_core: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  # - assets/images/svg
  # - assets/images/png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
