name: todo_app_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  dartz: ^0.10.1
  dio: ^4.0.6
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_svg: ^1.1.6
  form_builder_validators: ^8.4.0
  cloud_firestore: ^4.3.1
  syncfusion_flutter_datepicker: ^20.4.43
  table_calendar: ^3.0.8
  smooth_page_indicator: ^1.0.0+2
  accordion: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/json/
    - assets/images/svg/categories/
    - assets/images/png/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        # - asset: assets/fonts/Quicksand-Regular.ttf
        #   weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
