// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeaoomi5bOrdoYsd90vCn-dEFK23y3kY',
    appId: '1:111636486846:web:be7e31f51c88e0e84c9cef',
    messagingSenderId: '111636486846',
    projectId: 'todo-app-flutter-firebas-d71aa',
    authDomain: 'todo-app-flutter-firebas-d71aa.firebaseapp.com',
    storageBucket: 'todo-app-flutter-firebas-d71aa.appspot.com',
    measurementId: 'G-4Q3459GWGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmOeXN1NQlQbajZB-xO8eLTYgV-u8i0Y',
    appId: '1:111636486846:android:7089604d60b168b84c9cef',
    messagingSenderId: '111636486846',
    projectId: 'todo-app-flutter-firebas-d71aa',
    storageBucket: 'todo-app-flutter-firebas-d71aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArGF2xKNvNvJsW46vWR7gu4MpnoHsLIPg',
    appId: '1:111636486846:ios:492cac9ba53af4514c9cef',
    messagingSenderId: '111636486846',
    projectId: 'todo-app-flutter-firebas-d71aa',
    storageBucket: 'todo-app-flutter-firebas-d71aa.appspot.com',
    androidClientId: '111636486846-lcn4dg2mpm0gl7glnk6vdkqmr3ncotk2.apps.googleusercontent.com',
    iosClientId: '111636486846-hu18gpdilciqdql4gvorlaefvvhp7suq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArGF2xKNvNvJsW46vWR7gu4MpnoHsLIPg',
    appId: '1:111636486846:ios:492cac9ba53af4514c9cef',
    messagingSenderId: '111636486846',
    projectId: 'todo-app-flutter-firebas-d71aa',
    storageBucket: 'todo-app-flutter-firebas-d71aa.appspot.com',
    androidClientId: '111636486846-lcn4dg2mpm0gl7glnk6vdkqmr3ncotk2.apps.googleusercontent.com',
    iosClientId: '111636486846-hu18gpdilciqdql4gvorlaefvvhp7suq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFlutter',
  );
}
